apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: sql-vol
        persistentVolumeClaim:
          claimName: sql-pv-claim
      - name: influx-vol
        persistentVolumeClaim:
          claimName: influx-pv-claim
      - name: home-vol 
        persistentVolumeClaim:
          claimName: home-pv-claim
      containers:
      - name: nginx
        image: nginx:service
        volumeMounts:
        - name: sql-vol
          mountPath: /mnt/sql
        - name: influx-vol
          mountPath: /mnt/influx
        - name: home-vol
          mountPath: /home
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
  selector:
    app: nginx
  type: LoadBalancer
