apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    server {
        listen 80;
        listen [::]:80;
        return 301 https://$host$request_uri;
    }
    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        ssl_certificate /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;
        root /www;
        location /wordpress {
            return 307 https://$host:5050;
        }
        location /grafana {
            return 307 https://$host:3000;
        }
        location /phpmyadmin/ {
            proxy_set_header HOST $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            rewrite ^/phpmyadmin/(.*) /$1 break;
            proxy_pass https://phpmyadmin:5000;
        }
        error_page 497 https://$host$request_uri;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: sql-vol
        persistentVolumeClaim:
          claimName: sql-pv-claim
      - name: influx-vol
        persistentVolumeClaim:
          claimName: influx-pv-claim
      - name: home-vol 
        persistentVolumeClaim:
          claimName: home-pv-claim
      containers:
      - name: nginx
        image: nginx:service
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/nginx.conf
          subPath: nginx.conf
        - name: sql-vol
          mountPath: /mnt/sql
        - name: influx-vol
          mountPath: /mnt/influx
        - name: home-vol
          mountPath: /home
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
  selector:
    app: nginx
  type: LoadBalancer
