apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
  spec:
  replicas: 1
  selector:
    matchLabels:
    app: mysql
  template:
  metadata:
    name: mysql
    labels:
      app: mysql
    spec:
      volumes:
      - name: sql-vol
        persistentVolumeClaim:
          claimName: sql-pv-claim
      containers:
      - name: mysql
        image: mysql:service
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: sql-vol
          mountPath: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app: mysql
  type: ClusterIP
