apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      name: wordpress
      labels:
        app: wordpress
    spec:
      volumes:
      - name: sql-vol
        persistentVolumeClaim:
          claimName: sql-pv-claim
      - name: influx-vol
        persistentVolumeClaim:
          claimName: influx-pv-claim
      containers:
      - name: wordpress
        image: wordpress:service
        ports:
        - name: https
          containerPort: 5050
        volumeMounts:
        - name: sql-vol
          mountPath: /mnt/sql
        - name: influx-vol
          mountPath: /mnt/influx
---          
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: wordpress
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - name: https
    protocol: TCP
    port: 5050
    targetPort: 5050
