apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      name: wordpress
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:service
        ports:
        - name: https
          containerPort: 5050
---          
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - name: https
    protocol: TCP
    port: 5050
    targetPort: 5050
  selector:
    app: wordpress
  type: LoadBalancer
