apiVersion: v1
kind: PersistentVolume
metadata:
  name: ftps-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      name: ftps
      labels:
        app: ftps
    spec:
      volumes:
      - name: ftps-pv-volume
      containers:
      - name: ftps
        image: ftps:service
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 30020
        - containerPort: 30021
        volumeMounts:
        - name: ftps-pv-volume
          mountPath: /home/
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - protocol: TCP
    port: 20
    targetPort: 20
    name: ftp-data
  - protocol: TCP
    port: 21
    targetPort: 21
    name: ftp-21
  - protocol: TCP
    port: 30020
    targetPort: 30020
    name: ftp-passv-30020
  - protocol: TCP
    port: 30021
    targetPort: 30021
    name: ftp-passv-30021
