apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      name: ftps
      labels:
        app: ftps
    spec:
      volumes:
      - name: sql-vol
        persistentVolumeClaim:
          claimName: sql-pv-claim
      - name: home-vol 
        persistentVolumeClaim:
          claimName: home-pv-claim
      containers:
      - name: ftps
        image: ftps:service
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 30020
        - containerPort: 30021
        volumeMounts:
        - name: sql-vol
          mountPath: /mnt/sql
        - name: home-vol
          mountPath: /home
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - protocol: TCP
    port: 20
    targetPort: 20
    name: ftp-data
  - protocol: TCP
    port: 21
    targetPort: 21
    name: ftp-21
  - protocol: TCP
    port: 30020
    targetPort: 30020
    name: ftp-passv-30020
  - protocol: TCP
    port: 30021
    targetPort: 30021
    name: ftp-passv-30021
